### ISSUE TITLE
Crash with typst 0.12, equate.with(breakable:true)

### ISSUE THREAD

**Issue by behinger** [EpicEricEE/typst-equate#5] opened 2024-10-11 09:55 UTC
```typst
#import "@preview/equate:0.2.0": equate
#show: equate.with(breakable: true)

$ a \
& b
$
```

In a current document with a collaborator @ReneSkukies, I ran into this bug. This crashed ("The compiler crashed") in typst 0.12 but not typst 0.11. If I set `breakable: false` it works.

This is in the web-app, I dont know if I can get a stacktrace or similar

**Comment by EpicEricEE** [comment] 2024-10-11 10:13
Duplicate of #4

**Closed by EpicEricEE** 2024-10-11 10:13 UTC
